// <auto-generated />
namespace DevDays2016.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_for_User_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_for_User_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "201606150858461_update_for_User_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
