// <auto-generated />
namespace DevDays2016.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initDevDays2016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initDevDays2016));
        
        string IMigrationMetadata.Id
        {
            get { return "201606130750415_init-DevDays2016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
