// <auto-generated />
namespace DevDays2016.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_Questionnaire : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Questionnaire));
        
        string IMigrationMetadata.Id
        {
            get { return "201606160830392_add_Questionnaire"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
